### ISSUE TITLE
Impossible de scanner le domaine

### ISSUE THREAD

**Issue by JeedomPupu** [hugoKs3/plugin-noip#5]
Bonjour, 

Tout d'abord merci pour ce boulot, l'idée me plaisait bien car bien pratique !

Le seul "hic" est quand je lance le scann des noms de domaine j'ai le message suivant : 

"Le nom de l'équipement ne peut pas être vide : noip Object ( [id:protected] => [name:protected] => [logicalId:protected] => [generic_type:protected] => [object_id:protected] => 1 [eqType_name:protected] => noip [isVisible:protected] => 0 [isEnable:protected] => 1 [configuration:protected] => Array ( [type] => domain [login] => ********** [image] => plugins/noip/core/assets/domain_icon.png ) [timeout:protected] => 0 [category:protected] => [display:protected] => [order:protected] => 9999 [comment:protected] => [tags:protected] => [_debug:protected] => [_object:protected] => [_needRefreshWidget:protected] => 1 [_timeoutUpdated:protected] => [_batteryUpdated:protected] => [_changed:protected] => 1 )"

J'ai essayé de réinstaller les dépendances, de recréer l'équipement mais pas moyen...

Une idée ?  :) 

Merci d'avance.

**Comment by JeedomPupu** [comment]
Pour plus de précision (oui parce que ça ne se devine pas...) j'ai installé le plugin sur un RPI 4, avec la dernière version de Jeedom à jour.

Redites moi s'il faut plus d'information.

**Comment by hugoKs3** [comment]
Bonjour et merci pour votre retour.

Vous êtes de plus en plus nombreux à me reporter cette erreur depuis quelques jours.
Je ne vois pas, pour l’instant, d’où vient le pb sachant que le plugin n’a pas été mis à jour depuis plusieurs semaines…
Je manque un peu de temps en ce moment mais j’essaierai de regarder cette semaine.

Je vous propose de poursuivre cette discussion sur le forum où le problème a également été reporté : https://community.jeedom.com/t/nouveau-plugin-no-ip-renew/49829/69

Merci pour votre patience.
